import { useEffect, useState } from 'react';
import { useNavigate } from '@tanstack/react-router';
import { Check, Pencil, Headphones, ArrowUpRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useFunnel } from '@/lib/funnel/store';
import { PageIntro, DemoNotice } from './layout';
export function ChatPage({offer=false}:{offer?:boolean}) {
 const {state,update,track}=useFunnel();const navigate=useNavigate();const status=offer?state.preChat:state.assistant;
 const stage=!status.nameConfirmed?0:!status.objectiveConfirmed?1:2;
 const [visible,setVisible]=useState(0);const [typing,setTyping]=useState(true);
 const first=state.user.name.split(' ')[0];
 const messages=stage===0?[`Olá, ${first}! ${offer?'Antes de você continuar, quero confirmar rapidamente os dados que você acabou de informar.':'Vi que você acabou de concluir esta etapa.'}`,'Isso leva menos de um minuto.','Seu nome está correto?']:stage===1?['Perfeito.','Seu objetivo selecionado foi:',state.user.objective,'Está correto?']:['Ótimo. Vou deixar tudo pronto para a próxima etapa.','Essa confirmação serve para evitar erros no cadastro da demonstração e garantir que a próxima etapa corresponda às informações que você acabou de fornecer.','Podemos continuar?'];
 useEffect(()=>{setVisible(0);setTyping(true);const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;let count=0;const timer=window.setInterval(()=>{count++;setVisible(count);if(count>=messages.length){setTyping(false);window.clearInterval(timer);}},reduced?50:600);return()=>window.clearInterval(timer);},[stage,offer,messages.length]);
 const confirm=()=>{if(stage===0){update(s=>offer?({...s,preChat:{...s.preChat,nameConfirmed:true}}):({...s,assistant:{...s.assistant,nameConfirmed:true}}));track(offer?'offer_chat_name_confirmed':'name_confirmed');}else if(stage===1){update(s=>offer?({...s,preChat:{...s.preChat,objectiveConfirmed:true}}):({...s,assistant:{...s.assistant,objectiveConfirmed:true}}));track(offer?'offer_chat_objective_confirmed':'objective_confirmed');}else{if(offer){update(s=>({...s,preChat:{...s.preChat,completed:true}}));track('offer_chat_completed');navigate({to:'/final-confirmation'});}else navigate({to:'/confirmation'});}};
 const correction=()=>{update(s=>({...s,returnTo:offer?'/offer-chat':'/assistant'}));navigate({to:stage===0?'/edit-data':'/objective'});};
 return <section className="page-enter"><PageIntro eyebrow={offer?'ANTES DE CONTINUAR':'ATENDIMENTO'} title={offer?'Só uma última conversa.':'Vamos conferir juntos.'} description="Um cuidado a mais com as suas informações."/><div className="chat-window"><div className="chat-header"><div className="ana-avatar"><Headphones size={24}/><span className="online-dot"/></div><div><strong>Ana</strong><p>Assistente virtual · Atendimento automatizado</p></div><span className="chat-badge">DEMO</span></div><div className="chat-body" aria-live="polite"><p className="chat-date">Hoje</p>{messages.slice(0,visible).map((message,index)=><div className="assistant-bubble page-enter" key={`${stage}-${index}`}>{message}</div>)}{typing&&<div className="typing" role="status"><span/><span/><span/><small>digitando…</small></div>}{!typing&&<div className="chat-actions"><Button onClick={confirm} className="chat-confirm">{stage<2?'Sim, está correto':'Confirmar e continuar'}{stage<2?<Check size={17}/>:<ArrowUpRight size={17}/>}</Button>{stage<2&&<Button variant="ghost" onClick={correction}><Pencil size={15}/>{stage===0?'Corrigir':'Alterar'}</Button>}</div>}</div><div className="chat-footer">Atendimento automático, sem envio de mensagens a terceiros.</div></div><DemoNotice>Não solicitaremos senhas, códigos ou dados bancários.</DemoNotice></section>;
}