import { useEffect, useState } from 'react';
import { Link, useNavigate } from '@tanstack/react-router';
import { ArrowUpRight, Check, CheckCircle2, Target, ListChecks, SlidersHorizontal, ShieldCheck, Clock3, LoaderCircle, FileCheck2, ChevronDown, Headphones, CircleCheck } from 'lucide-react';
import { Button } from '@/components/ui/button';
import cards from '@/assets/planning-cards.jpg';
import { useFunnel } from '@/lib/funnel/store';
import { guardPath, steps, OFFER_CONFIG, needsDownsell, selectedItems, totalPrice, priceLabel, type Path } from '@/lib/funnel/model';
import { readEvents, viewEvents } from '@/lib/funnel/analytics';
import { DemoNotice, PageIntro, Primary, ResetButton } from './layout';
import { QuestionPage, EditPage, type QuestionPath } from './question';
import { ChatPage } from './chat';
export function FunnelPage({path}:{path:Path}) {
 const {state,ready,update,track}=useFunnel();const navigate=useNavigate(); const blocked=ready?guardPath(path,state):null;
 useEffect(()=>{if(!ready)return;if(blocked){navigate({to:blocked,replace:true});return;}if(path==='/assistant-offer'){navigate({to:'/offer-chat',replace:true});return;}const index=steps.indexOf(path as typeof steps[number]);if(index>=0)update(s=>({...s,progress:{...s.progress,currentStep:index,lastPath:path as typeof steps[number]}}));const event=viewEvents[path];if(event)track(event);
 if(path==='/offer')update(s=>({...s,offer:{...s.offer,viewed:true}}));if(path==='/assistant')update(s=>({...s,assistant:{...s.assistant,started:true}}));if(path==='/checkout')update(s=>({...s,checkout:{...s.checkout,started:true}}));if(path==='/upsell-1')update(s=>({...s,upsell1:{...s.upsell1,viewed:true}}));if(path==='/upsell-2')update(s=>({...s,upsell2:{...s.upsell2,viewed:true}}));if(path==='/downsell')update(s=>({...s,downsell:{...s.downsell,viewed:true}}));if(path==='/final-offer')update(s=>({...s,finalOffer:{viewed:true}}));
 },[path,ready,blocked,navigate,update,track]);
 if(!ready||blocked)return <div className="loading-screen" role="status">Preparando sua etapa…</div>;
 if(['/name','/birth-date','/objective','/income','/professional-status'].includes(path))return <QuestionPage key={path} path={path as QuestionPath}/>;
 if(path==='/edit-data')return <EditPage/>;
 if(path==='/assistant'||path==='/offer-chat')return <ChatPage key={path} offer={path==='/offer-chat'}/>;
 if(path==='/')return <Landing/>;
 if(path==='/start')return <section className="page-enter"><PageIntro eyebrow="UM NOVO COMEÇO" title="Vamos começar" description="Algumas perguntas para organizar seu perfil e personalizar esta demonstração." icon={<SlidersHorizontal size={26}/>}/><div className="feature-list">{[['5 perguntas rápidas','Um passo de cada vez.'],['Do seu jeito','Suas respostas orientam a demonstração.'],['Sem compromisso','Nenhuma cobrança ou análise financeira real.']].map(([t,d],i)=><div className="feature-row" key={t}><span className="step-disc">0{i+1}</span><div><strong>{t}</strong><p>{d}</p></div></div>)}</div><Primary onClick={()=>{track('funnel_started');navigate({to:'/name'});}}>Continuar</Primary><DemoNotice/></section>;
 if(path==='/analysis')return <Analysis/>;
 if(path==='/result')return <section className="page-enter"><PageIntro eyebrow="SEU PERFIL ESTÁ ORGANIZADO" title="Análise concluída" description="Com base nas informações fornecidas, preparamos uma demonstração personalizada para você." icon={<CheckCircle2 size={26}/>}/><Profile/><Primary onClick={()=>navigate({to:'/assistant'})}>Continuar</Primary><DemoNotice>Resultado demonstrativo. Não representa aprovação financeira.</DemoNotice></section>;
 if(path==='/confirmation'||path==='/final-confirmation'){const final=path==='/final-confirmation';return <section className="page-enter"><PageIntro eyebrow={final?'ÚLTIMA CONFERÊNCIA':'SEUS DADOS'} title={final?'Tudo correto para continuar?':'Confirme suas informações'} description="Confira o resumo. Você pode corrigir qualquer informação antes de seguir." icon={<FileCheck2 size={26}/>}/><Profile/><Button variant="link" onClick={()=>{update(s=>({...s,returnTo:final?'/offer-chat':'/assistant'}));navigate({to:'/edit-data'});}}>Corrigir meus dados</Button><Primary onClick={()=>{update(s=>final?({...s,preChat:{...s.preChat,finalConfirmed:true}}):({...s,assistant:{...s.assistant,dataConfirmed:true}}));track(final?'final_data_confirmed':'data_confirmed');navigate({to:final?'/checkout':'/mechanism'});}}>Confirmar e continuar</Primary><DemoNotice/></section>;}
 if(path==='/mechanism')return <section><PageIntro eyebrow="TRANSPARÊNCIA EM CADA ETAPA" title="Como funciona?" description="Você está no controle, do início ao fim."/><div className="feature-list">{[['Você informa seus objetivos','Cinco perguntas para conhecer seu momento.'],['Organizamos suas respostas','Sem consulta a bancos ou análise de crédito.'],['Apresentamos a demonstração','Uma oferta de exemplo, com escolha livre.'],['Você decide como continuar','Todos os pagamentos são apenas simulados.']].map(([t,d],i)=><div className="feature-row" key={t}><span className="step-disc">{i+1}</span><div><strong>{t}</strong><p>{d}</p></div></div>)}</div><Primary onClick={()=>navigate({to:'/offer'})}>Ver minha oferta</Primary></section>;
 if(path==='/offer')return <Offer/>;
 if(path==='/checkout')return <Checkout/>;
 if(path==='/upsell-1'||path==='/upsell-2'||path==='/downsell')return <Upsell key={path} path={path}/>;
 if(path==='/final-offer'||path==='/success')return <Summary success={path==='/success'}/>;
 if(path==='/privacy'||path==='/terms')return <Legal privacy={path==='/privacy'}/>;
 if(path==='/admin')return <Admin/>;
 return null;
}
function Landing(){const {state,track,reset}=useFunnel();const navigate=useNavigate();const resume=state.progress.lastPath!=='/'&&state.progress.lastPath!=='/success';return <section className="landing page-enter"><div className="landing-heading"><p className="eyebrow"><span className="eyebrow-line"/>SEU PRÓXIMO PASSO COMEÇA AQUI</p><h1>Mais clareza para<br/>a sua vida financeira<span className="brand-dot">.</span></h1><p>Conheça seu perfil. Organize seus objetivos.<br className="hidden sm:block"/> Explore uma jornada feita a partir de você.</p></div><div className="landing-image"><img src={cards} alt="Cartões ilustrativos em tons lilás e verde, sem vínculo bancário" width={1024} height={1024}/><span className="image-label"><ShieldCheck size={14}/>Demonstração independente</span></div><div className="landing-cta"><Primary onClick={()=>{track('funnel_started');navigate({to:'/start'});}}>Começar agora</Primary><span className="time-note"><Clock3 size={14}/>Poucos minutos · Sem compromisso</span>{resume&&<Button variant="outline" className="w-full mt-4" onClick={()=>navigate({to:state.progress.lastPath})}>Retomar minha jornada<ArrowUpRight/></Button>}{state.finished&&<Button variant="link" onClick={()=>{reset();navigate({to:'/start'});}}>Iniciar nova demonstração</Button>}</div><div className="landing-benefits"><div className="section-caption"><span>UM PASSO DE CADA VEZ</span><span>01 — 03</span></div><h2>Simples. Pessoal. Transparente.</h2>{[[Target,'Seu objetivo em primeiro lugar','Uma jornada guiada pelo que importa para você.'],[ListChecks,'Tudo bem organizado','Suas informações reunidas em um só lugar.'],[ShieldCheck,'Você no controle','Sem senhas, dados bancários ou cobranças reais.']].map(([Icon,t,d])=>{const I=Icon as typeof Target;return <div className="benefit" key={String(t)}><span className="benefit-icon"><I size={20}/></span><div><h3>{String(t)}</h3><p>{String(d)}</p></div><ArrowUpRight className="benefit-arrow" size={17}/></div>;})}</div><div className="landing-bottom"><Headphones size={20}/><p>Uma assistente virtual acompanha<br/>as confirmações da sua jornada.</p></div></section>;}
function Profile(){const {state}=useFunnel();return <dl className="profile-summary">{[['Nome',state.user.name],['Data de nascimento',state.user.birthDate],['Objetivo',state.user.objective],['Renda mensal',state.user.incomeRange],['Situação profissional',state.user.professionalStatus]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>;}
function Analysis(){const {update,track}=useFunnel();const navigate=useNavigate();const [count,setCount]=useState(0);useEffect(()=>{const timer=setInterval(()=>setCount(c=>Math.min(4,c+1)),650);return()=>clearInterval(timer);},[]);useEffect(()=>{if(count!==4)return;update(s=>({...s,progress:{...s.progress,completedSteps:[...new Set([...s.progress.completedSteps,'/analysis'])]}}));track('analysis_completed');const timer=setTimeout(()=>navigate({to:'/result'}),500);return()=>clearTimeout(timer);},[count,update,track,navigate]);return <section className="analysis-page"><div className="analysis-symbol"><LoaderCircle size={40} className="spin"/></div><PageIntro title="Analisando suas respostas…" description="Organizando as informações da sua demonstração."/><div className="analysis-list" aria-live="polite">{['Informações recebidas','Perfil organizado','Objetivo identificado','Preparando demonstração'].map((text,i)=><div className={i<count?'analysis-done':''} key={text}>{i<count?<CheckCircle2 size={19}/>:<span className="empty-circle"/>}{text}</div>)}</div><DemoNotice>Sem consulta de crédito ou verificação de identidade real.</DemoNotice></section>;}
function Offer(){const {state,update}=useFunnel();const navigate=useNavigate();return <section className="page-enter"><PageIntro eyebrow="PREPARADO PARA O SEU MOMENTO" title="Sua próxima etapa, com mais clareza." description={`Uma demonstração alinhada ao seu objetivo: ${state.user.objective.toLowerCase()}.`}/><div className="offer-item"><div className="offer-top"><span className="offer-tag">OFERTA DEMONSTRATIVA</span><Target size={25}/></div><h2>{OFFER_CONFIG.main.name}</h2><p className="muted-copy">Informações organizadas para você seguir com confiança.</p><Benefits benefits={OFFER_CONFIG.main.benefits}/><div className="price-block"><span>Preço da oferta</span><strong>{priceLabel(OFFER_CONFIG.main.price)}</strong><small>Produto e preço comercial ainda não configurados.</small></div></div><Primary onClick={()=>{update(s=>({...s,offer:{...s.offer,accepted:true}}));navigate({to:'/offer-chat'});}}>Continuar</Primary><DemoNotice>Antes de continuar, Ana confirmará seus dados.</DemoNotice><FAQ/></section>;}
function Benefits({benefits}:{benefits:string[]}){return <ul className="benefits-list">{benefits.map(b=><li key={b}><Check size={17}/><span>{b}</span></li>)}</ul>;}
function FAQ(){return <div className="faq"><h2>Dúvidas frequentes</h2>{[['Existe alguma cobrança?','Não. Toda a jornada é demonstrativa, sem movimentação de dinheiro.'],['Isso é uma aprovação de crédito?','Não. Nenhuma instituição financeira analisa suas respostas.'],['Onde ficam minhas informações?','Somente neste navegador. Você pode excluí-las na página de privacidade.']].map(([q,a])=><details key={q}><summary>{q}<ChevronDown size={16}/></summary><p>{a}</p></details>)}</div>;}
function Checkout(){const {state,update,track}=useFunnel();const navigate=useNavigate();const [scenario,setScenario]=useState('success');const status=state.checkout.status;
 useEffect(()=>{if(status!=='processing')return;const timer=setTimeout(()=>{const next=scenario==='success'?'demo-success':scenario==='pending'?'pending':'error';update(s=>({...s,checkout:{...s.checkout,status:next}}));track(next==='demo-success'?'payment_demo_completed':next==='error'?'payment_error':'payment_demo_pending');},1200);return()=>clearTimeout(timer);},[status,scenario,update,track]);
 return <section className="page-enter"><PageIntro eyebrow="CHECKOUT DEMONSTRATIVO" title={status==='demo-success'?'Pagamento demonstrativo concluído':'Confira antes de continuar'} description="Não há cobrança real ou movimentação financeira." icon={<ShieldCheck size={26}/>}/><div className="checkout-summary"><span>Resumo da oferta</span><h2>{OFFER_CONFIG.main.name}</h2><div><span>Valor</span><strong>{priceLabel(OFFER_CONFIG.main.price)}</strong></div><div><span>Forma de pagamento</span><strong>Simulação sem cobrança</strong></div></div>{status==='error'&&<p role="alert" className="field-error">Erro demonstrativo. Nenhum valor foi cobrado. Você pode tentar novamente.</p>}{status==='pending'&&<p role="status" className="notice">Simulação pendente. Nenhum valor foi cobrado.</p>}{status==='demo-success'?<Primary onClick={()=>navigate({to:'/upsell-1'})}>Continuar</Primary>:<><label className="scenario-label" htmlFor="scenario">Cenário de demonstração</label><select id="scenario" value={scenario} disabled={status==='processing'} onChange={e=>setScenario(e.target.value)}><option value="success">Conclusão demonstrativa</option><option value="pending">Pagamento pendente</option><option value="error">Erro no processamento</option></select><Primary loading={status==='processing'} onClick={()=>{track('payment_demo_started');update(s=>({...s,checkout:{...s.checkout,status:'processing'}}));}}>{status==='processing'?<><LoaderCircle className="spin"/>Processando…</>:status==='idle'?'Simular conclusão':'Tentar novamente'}</Primary></>}<DemoNotice>Não informe dados de cartão, banco ou códigos de segurança.</DemoNotice></section>;}
function Upsell({path}:{path:'/upsell-1'|'/upsell-2'|'/downsell'}){const {state,update,track}=useFunnel();const navigate=useNavigate();const key=path==='/upsell-1'?'upsell1':path==='/upsell-2'?'upsell2':'downsell';const config=OFFER_CONFIG[key];const decide=(accepted:boolean)=>{update(s=>({...s,[key]:{viewed:true,accepted}}));track(`${key}_${accepted?'accepted':'declined'}`);navigate({to:key==='upsell1'?'/upsell-2':key==='upsell2'?(needsDownsell({...state,upsell2:{viewed:true,accepted}})?'/downsell':'/final-offer'):'/final-offer'});};return <section className="page-enter"><PageIntro eyebrow={key==='downsell'?'UMA ALTERNATIVA OPCIONAL':'CONTINUE DO SEU JEITO'} title={key==='downsell'?'Antes de você sair…':key==='upsell1'?'Um complemento para sua jornada.':'Uma segunda opção para você.'} description="Você pode aceitar ou recusar. Sua escolha não impede a conclusão."/><div className="offer-item"><span className="offer-tag">{key==='downsell'?'ALTERNATIVA SIMPLIFICADA':'OFERTA OPCIONAL'}</span><h2>{config.name}</h2><Benefits benefits={config.benefits}/><div className="price-block"><span>Preço</span><strong>{priceLabel(config.price)}</strong><small>Sem cobrança nesta demonstração.</small></div></div><Primary onClick={()=>decide(true)}>{key==='upsell1'?'Adicionar à minha compra':key==='upsell2'?'Quero adicionar':'Aproveitar esta opção'}</Primary><Button variant="ghost" className="decline-button" onClick={()=>decide(false)}>{key==='upsell2'?'Não, obrigado':'Não quero'}</Button><DemoNotice/></section>;}
function Summary({success}:{success:boolean}){const {state,update,track,reset}=useFunnel();const navigate=useNavigate();const items=selectedItems(state);const total=totalPrice(items);return <section className="page-enter"><PageIntro eyebrow={success?'JORNADA CONCLUÍDA':'TUDO EM UM SÓ LUGAR'} title={success?'Tudo certo!':'Seu pedido está pronto'} description={success?'Sua jornada foi concluída. Confira o resumo da demonstração.':'Confira apenas as opções que você selecionou.'} icon={<CircleCheck size={30}/>}/><div className="order-summary">{items.map(item=><div key={item.name}><span>{item.name}</span><strong>{priceLabel(item.price)}</strong></div>)}<div className="order-total"><span>Total demonstrativo</span><strong>{total===null?'Não definido':priceLabel(total)}</strong></div></div><p className="muted-copy">Nenhuma compra, contratação ou cobrança real foi realizada.</p><Primary onClick={()=>{if(success){reset();navigate({to:'/'});}else{update(s=>({...s,finished:true}));track('funnel_completed');navigate({to:'/success'});}}}>{success?'Voltar ao início':'Continuar'}</Primary><DemoNotice/></section>;}
function Legal({privacy}:{privacy:boolean}){return <section className="legal"><PageIntro eyebrow="DEMONSTRAÇÃO INDEPENDENTE" title={privacy?'Sua privacidade importa.':'Termos da demonstração'}/>{privacy?<><h2>Quais informações são usadas?</h2><p>Nome, data de nascimento, objetivo, faixa aproximada de renda e situação profissional. Você pode usar informações fictícias para testar.</p><h2>Para que servem?</h2><p>Para personalizar o resumo e as confirmações do atendimento automatizado. Não consultamos bancos nem realizamos análises de crédito.</p><h2>Onde são armazenadas?</h2><p>As respostas, escolhas e progresso ficam no armazenamento local deste navegador. As métricas locais registram um identificador de sessão, eventos e horário, sem incluir suas respostas. Nenhuma informação é enviada a um serviço financeiro.</p><h2>Como excluir?</h2><p>O botão abaixo apaga as respostas e métricas salvas neste navegador. Limpar os dados do site no navegador também remove as informações.</p><ResetButton/></>:<><h2>Projeto não oficial</h2><p>Este projeto é uma demonstração independente e não representa ou é afiliado à Revolut ou a qualquer instituição financeira.</p><h2>Sem serviços financeiros reais</h2><p>Não oferecemos crédito, seguros ou serviços bancários. Os resultados não constituem aprovação ou recomendação financeira.</p><h2>Pagamento apenas demonstrativo</h2><p>Todos os pagamentos e aceites são simulados. Não geram cobrança, contratação, tributos, cobertura de seguro ou obrigação financeira.</p><h2>Preços e ofertas</h2><p>Os produtos comerciais e valores em reais ainda não foram definidos. Não há desconto, garantia comercial ou promessa de liberação de recursos.</p><h2>Contacto</h2><p>Contacto ainda não configurado. Para excluir informações locais, acesse a página de privacidade.</p><Button asChild variant="outline"><Link to="/privacy">Privacidade e exclusão de dados</Link></Button></>}</section>;}
function Admin(){const [events]=useState(readEvents);const sessions=new Set(events.map(e=>e.sessionId)).size;const count=(name:string)=>new Set(events.filter(e=>e.name===name).map(e=>e.sessionId)).size;const metrics=[['Landing','landing_view'],['Início','funnel_started'],['Questionário','professional_status_selected'],['Análise','analysis_completed'],['Resultado','result_viewed'],['Atendimento','assistant_started'],['Dados confirmados','data_confirmed'],['Mecanismo','mechanism_viewed'],['Oferta','offer_viewed'],['Chat pré-checkout','offer_chat_started'],['Chat concluído','offer_chat_completed'],['Checkout','checkout_started'],['Pagamento demo','payment_demo_completed'],['Upsell 1 aceito','upsell1_accepted'],['Upsell 2 aceito','upsell2_accepted'],['Downsell aceito','downsell_accepted'],['Resumo final','final_offer_viewed'],['Sucesso','funnel_completed']];return <section><PageIntro eyebrow="MÉTRICAS LOCAIS · DEMONSTRAÇÃO" title="Visão da jornada" description="Somente sessões registradas neste navegador. Não é um painel global ou uma área administrativa protegida."/><div className="metric-grid">{[['Sessões',sessions],['Inícios',count('funnel_started')],['Concluídos',count('funnel_completed')]].map(([label,value])=><div className="metric" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><h2 className="section-title">Conversão por etapa</h2><div className="conversion-list">{metrics.map(([label='',event=''],i)=>{const n=count(event);const previous=i?count(metrics[i-1]?.[1] ?? ''):n;return <div key={event}><div className="conversion-label"><span>{label}</span><strong>{n} <small>{previous?Math.round(n/previous*100):0}%</small></strong></div><progress max={Math.max(sessions,1)} value={n}/></div>;})}</div><DemoNotice>Etapas condicionais e aceites têm públicos diferentes; as taxas podem variar.</DemoNotice></section>;}