/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AssistantOfferRouteImport } from './routes/assistant-offer'
import { Route as BirthDateRouteImport } from './routes/birth-date'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as DownsellRouteImport } from './routes/downsell'
import { Route as EditDataRouteImport } from './routes/edit-data'
import { Route as FinalConfirmationRouteImport } from './routes/final-confirmation'
import { Route as FinalOfferRouteImport } from './routes/final-offer'
import { Route as IncomeRouteImport } from './routes/income'
import { Route as MechanismRouteImport } from './routes/mechanism'
import { Route as NameRouteImport } from './routes/name'
import { Route as ObjectiveRouteImport } from './routes/objective'
import { Route as OfferRouteImport } from './routes/offer'
import { Route as OfferChatRouteImport } from './routes/offer-chat'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfessionalStatusRouteImport } from './routes/professional-status'
import { Route as ResultRouteImport } from './routes/result'
import { Route as StartRouteImport } from './routes/start'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as Upsell1RouteImport } from './routes/upsell-1'
import { Route as Upsell2RouteImport } from './routes/upsell-2'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantOfferRoute = AssistantOfferRouteImport.update({
  id: '/assistant-offer',
  path: '/assistant-offer',
  getParentRoute: () => rootRouteImport,
} as any)
const BirthDateRoute = BirthDateRouteImport.update({
  id: '/birth-date',
  path: '/birth-date',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const DownsellRoute = DownsellRouteImport.update({
  id: '/downsell',
  path: '/downsell',
  getParentRoute: () => rootRouteImport,
} as any)
const EditDataRoute = EditDataRouteImport.update({
  id: '/edit-data',
  path: '/edit-data',
  getParentRoute: () => rootRouteImport,
} as any)
const FinalConfirmationRoute = FinalConfirmationRouteImport.update({
  id: '/final-confirmation',
  path: '/final-confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const FinalOfferRoute = FinalOfferRouteImport.update({
  id: '/final-offer',
  path: '/final-offer',
  getParentRoute: () => rootRouteImport,
} as any)
const IncomeRoute = IncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => rootRouteImport,
} as any)
const MechanismRoute = MechanismRouteImport.update({
  id: '/mechanism',
  path: '/mechanism',
  getParentRoute: () => rootRouteImport,
} as any)
const NameRoute = NameRouteImport.update({
  id: '/name',
  path: '/name',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectiveRoute = ObjectiveRouteImport.update({
  id: '/objective',
  path: '/objective',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferRoute = OfferRouteImport.update({
  id: '/offer',
  path: '/offer',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferChatRoute = OfferChatRouteImport.update({
  id: '/offer-chat',
  path: '/offer-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalStatusRoute = ProfessionalStatusRouteImport.update({
  id: '/professional-status',
  path: '/professional-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const Upsell1Route = Upsell1RouteImport.update({
  id: '/upsell-1',
  path: '/upsell-1',
  getParentRoute: () => rootRouteImport,
} as any)
const Upsell2Route = Upsell2RouteImport.update({
  id: '/upsell-2',
  path: '/upsell-2',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analysis': typeof AnalysisRoute
  '/assistant': typeof AssistantRoute
  '/assistant-offer': typeof AssistantOfferRoute
  '/birth-date': typeof BirthDateRoute
  '/checkout': typeof CheckoutRoute
  '/confirmation': typeof ConfirmationRoute
  '/downsell': typeof DownsellRoute
  '/edit-data': typeof EditDataRoute
  '/final-confirmation': typeof FinalConfirmationRoute
  '/final-offer': typeof FinalOfferRoute
  '/income': typeof IncomeRoute
  '/mechanism': typeof MechanismRoute
  '/name': typeof NameRoute
  '/objective': typeof ObjectiveRoute
  '/offer': typeof OfferRoute
  '/offer-chat': typeof OfferChatRoute
  '/privacy': typeof PrivacyRoute
  '/professional-status': typeof ProfessionalStatusRoute
  '/result': typeof ResultRoute
  '/start': typeof StartRoute
  '/success': typeof SuccessRoute
  '/terms': typeof TermsRoute
  '/upsell-1': typeof Upsell1Route
  '/upsell-2': typeof Upsell2Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analysis': typeof AnalysisRoute
  '/assistant': typeof AssistantRoute
  '/assistant-offer': typeof AssistantOfferRoute
  '/birth-date': typeof BirthDateRoute
  '/checkout': typeof CheckoutRoute
  '/confirmation': typeof ConfirmationRoute
  '/downsell': typeof DownsellRoute
  '/edit-data': typeof EditDataRoute
  '/final-confirmation': typeof FinalConfirmationRoute
  '/final-offer': typeof FinalOfferRoute
  '/income': typeof IncomeRoute
  '/mechanism': typeof MechanismRoute
  '/name': typeof NameRoute
  '/objective': typeof ObjectiveRoute
  '/offer': typeof OfferRoute
  '/offer-chat': typeof OfferChatRoute
  '/privacy': typeof PrivacyRoute
  '/professional-status': typeof ProfessionalStatusRoute
  '/result': typeof ResultRoute
  '/start': typeof StartRoute
  '/success': typeof SuccessRoute
  '/terms': typeof TermsRoute
  '/upsell-1': typeof Upsell1Route
  '/upsell-2': typeof Upsell2Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analysis': typeof AnalysisRoute
  '/assistant': typeof AssistantRoute
  '/assistant-offer': typeof AssistantOfferRoute
  '/birth-date': typeof BirthDateRoute
  '/checkout': typeof CheckoutRoute
  '/confirmation': typeof ConfirmationRoute
  '/downsell': typeof DownsellRoute
  '/edit-data': typeof EditDataRoute
  '/final-confirmation': typeof FinalConfirmationRoute
  '/final-offer': typeof FinalOfferRoute
  '/income': typeof IncomeRoute
  '/mechanism': typeof MechanismRoute
  '/name': typeof NameRoute
  '/objective': typeof ObjectiveRoute
  '/offer': typeof OfferRoute
  '/offer-chat': typeof OfferChatRoute
  '/privacy': typeof PrivacyRoute
  '/professional-status': typeof ProfessionalStatusRoute
  '/result': typeof ResultRoute
  '/start': typeof StartRoute
  '/success': typeof SuccessRoute
  '/terms': typeof TermsRoute
  '/upsell-1': typeof Upsell1Route
  '/upsell-2': typeof Upsell2Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analysis'
    | '/assistant'
    | '/assistant-offer'
    | '/birth-date'
    | '/checkout'
    | '/confirmation'
    | '/downsell'
    | '/edit-data'
    | '/final-confirmation'
    | '/final-offer'
    | '/income'
    | '/mechanism'
    | '/name'
    | '/objective'
    | '/offer'
    | '/offer-chat'
    | '/privacy'
    | '/professional-status'
    | '/result'
    | '/start'
    | '/success'
    | '/terms'
    | '/upsell-1'
    | '/upsell-2'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analysis'
    | '/assistant'
    | '/assistant-offer'
    | '/birth-date'
    | '/checkout'
    | '/confirmation'
    | '/downsell'
    | '/edit-data'
    | '/final-confirmation'
    | '/final-offer'
    | '/income'
    | '/mechanism'
    | '/name'
    | '/objective'
    | '/offer'
    | '/offer-chat'
    | '/privacy'
    | '/professional-status'
    | '/result'
    | '/start'
    | '/success'
    | '/terms'
    | '/upsell-1'
    | '/upsell-2'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analysis'
    | '/assistant'
    | '/assistant-offer'
    | '/birth-date'
    | '/checkout'
    | '/confirmation'
    | '/downsell'
    | '/edit-data'
    | '/final-confirmation'
    | '/final-offer'
    | '/income'
    | '/mechanism'
    | '/name'
    | '/objective'
    | '/offer'
    | '/offer-chat'
    | '/privacy'
    | '/professional-status'
    | '/result'
    | '/start'
    | '/success'
    | '/terms'
    | '/upsell-1'
    | '/upsell-2'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnalysisRoute: typeof AnalysisRoute
  AssistantRoute: typeof AssistantRoute
  AssistantOfferRoute: typeof AssistantOfferRoute
  BirthDateRoute: typeof BirthDateRoute
  CheckoutRoute: typeof CheckoutRoute
  ConfirmationRoute: typeof ConfirmationRoute
  DownsellRoute: typeof DownsellRoute
  EditDataRoute: typeof EditDataRoute
  FinalConfirmationRoute: typeof FinalConfirmationRoute
  FinalOfferRoute: typeof FinalOfferRoute
  IncomeRoute: typeof IncomeRoute
  MechanismRoute: typeof MechanismRoute
  NameRoute: typeof NameRoute
  ObjectiveRoute: typeof ObjectiveRoute
  OfferRoute: typeof OfferRoute
  OfferChatRoute: typeof OfferChatRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfessionalStatusRoute: typeof ProfessionalStatusRoute
  ResultRoute: typeof ResultRoute
  StartRoute: typeof StartRoute
  SuccessRoute: typeof SuccessRoute
  TermsRoute: typeof TermsRoute
  Upsell1Route: typeof Upsell1Route
  Upsell2Route: typeof Upsell2Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant-offer': {
      id: '/assistant-offer'
      path: '/assistant-offer'
      fullPath: '/assistant-offer'
      preLoaderRoute: typeof AssistantOfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/birth-date': {
      id: '/birth-date'
      path: '/birth-date'
      fullPath: '/birth-date'
      preLoaderRoute: typeof BirthDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downsell': {
      id: '/downsell'
      path: '/downsell'
      fullPath: '/downsell'
      preLoaderRoute: typeof DownsellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-data': {
      id: '/edit-data'
      path: '/edit-data'
      fullPath: '/edit-data'
      preLoaderRoute: typeof EditDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/final-confirmation': {
      id: '/final-confirmation'
      path: '/final-confirmation'
      fullPath: '/final-confirmation'
      preLoaderRoute: typeof FinalConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/final-offer': {
      id: '/final-offer'
      path: '/final-offer'
      fullPath: '/final-offer'
      preLoaderRoute: typeof FinalOfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/income': {
      id: '/income'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof IncomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mechanism': {
      id: '/mechanism'
      path: '/mechanism'
      fullPath: '/mechanism'
      preLoaderRoute: typeof MechanismRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/name': {
      id: '/name'
      path: '/name'
      fullPath: '/name'
      preLoaderRoute: typeof NameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objective': {
      id: '/objective'
      path: '/objective'
      fullPath: '/objective'
      preLoaderRoute: typeof ObjectiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer': {
      id: '/offer'
      path: '/offer'
      fullPath: '/offer'
      preLoaderRoute: typeof OfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer-chat': {
      id: '/offer-chat'
      path: '/offer-chat'
      fullPath: '/offer-chat'
      preLoaderRoute: typeof OfferChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professional-status': {
      id: '/professional-status'
      path: '/professional-status'
      fullPath: '/professional-status'
      preLoaderRoute: typeof ProfessionalStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upsell-1': {
      id: '/upsell-1'
      path: '/upsell-1'
      fullPath: '/upsell-1'
      preLoaderRoute: typeof Upsell1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upsell-2': {
      id: '/upsell-2'
      path: '/upsell-2'
      fullPath: '/upsell-2'
      preLoaderRoute: typeof Upsell2RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnalysisRoute: AnalysisRoute,
  AssistantRoute: AssistantRoute,
  AssistantOfferRoute: AssistantOfferRoute,
  BirthDateRoute: BirthDateRoute,
  CheckoutRoute: CheckoutRoute,
  ConfirmationRoute: ConfirmationRoute,
  DownsellRoute: DownsellRoute,
  EditDataRoute: EditDataRoute,
  FinalConfirmationRoute: FinalConfirmationRoute,
  FinalOfferRoute: FinalOfferRoute,
  IncomeRoute: IncomeRoute,
  MechanismRoute: MechanismRoute,
  NameRoute: NameRoute,
  ObjectiveRoute: ObjectiveRoute,
  OfferRoute: OfferRoute,
  OfferChatRoute: OfferChatRoute,
  PrivacyRoute: PrivacyRoute,
  ProfessionalStatusRoute: ProfessionalStatusRoute,
  ResultRoute: ResultRoute,
  StartRoute: StartRoute,
  SuccessRoute: SuccessRoute,
  TermsRoute: TermsRoute,
  Upsell1Route: Upsell1Route,
  Upsell2Route: Upsell2Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}